# Generated by Django 4.2.9 on 2026-03-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careplan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='additional_diagnoses',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='patient',
            name='primary_diagnosis',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='sex',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='weight_kg',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
